data:
  id: "DKYoon/SlimPajama-6B"
  cache_dir: "gs://levanter-will-data/tokenized/llama2-slimpj/"
  tokenizer: "meta-llama/Llama-2-7b-hf"
# Baseline loss is 1.780719581246376
model:
  r: 64
  attn_backend: jax_flash
  tokenizer: "meta-llama/Llama-2-7b-hf"
# TODO: uncomment this once we resolve the resource exhaustion issue
# initialize_from_hf: "meta-llama/Llama-2-7b-hf"
# use_hf_model_config: true
initialize_from_hf: "meta-llama/Llama-2-7b-hf"
trainer:
  tracker:
    type: wandb
    project: "levanter"
    tags: ["slimpj", "llamasg"]

  mp: p=f32,c=bfloat16
  train_batch_size: 2048 # 4m tokens per batch
  per_device_parallelism: 16
  num_train_steps: 1000 # 4b tokens
  steps_per_eval: 50
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
optimizer:
  learning_rate: 6E-4
  weight_decay: 0.1
  min_lr_ratio: 0.1
  lr_schedule: "constant"
