data:
  id: "DKYoon/SlimPajama-6B"
  cache_dir: "gs://levanter-will-data/tokenized/llama2-slimpj/"
  tokenizer: "meta-llama/Llama-2-7b-hf"
# Baseline loss is 1.780719581246376
model:
  seq_len: 4096
  r: 64
  attn_backend: splash
  tokenizer: "meta-llama/Llama-2-7b-hf"
# TODO: uncomment this once we resolve the resource exhaustion issue
# initialize_from_hf: "meta-llama/Llama-2-7b-hf"
# use_hf_model_config: true
initialize_from_hf: "meta-llama/Llama-2-7b-hf"
skip_after_k_tokens: 64
eval_loss_mask_after_k_tokens: 64
full_ft: False
trainer:
  tracker:
    type: wandb
    project: "levanter"
    tags: ["slimpj", "llamasg"]

  mp: p=f32,c=bfloat16
  train_batch_size: 1024 # 4m tokens per batch
  num_train_steps: 476 # 2b tokens
  steps_per_eval: 50
  per_device_parallelism: 8
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
  max_loss: 3.2
optimizer:
  learning_rate: 6E-4
  weight_decay: 0.1
  min_lr_ratio: 0.1
  warmup: 0.05
  lr_schedule: "cosine"
