data:
  id: "DKYoon/SlimPajama-6B"
  cache_dir: "gs://levanter-will-data/tokenized/llama2-slimpj/"
  tokenizer: "meta-llama/Llama-2-7b-hf"
model:
  type: llama
  seq_len: 4096
  hidden_dim: 896
  intermediate_dim: 2240
  num_heads: 7
  num_kv_heads: 7
  num_layers: 18
  tie_word_embeddings: true
  attn_backend: splash
trainer:
  tracker:
    project: "levanter"
    tags: ["lrsweep"]
  mp: p=f32,c=bfloat16
  train_batch_size: 32
  num_train_steps: 100
  steps_per_eval: 50
  fsdp_axis: null
  batch_axis: "batch"
  checkpointer:
    save_interval: 2h
