data:
  id: "DKYoon/SlimPajama-6B"
  cache_dir: "gs://levanter-will-data/tokenized/llama2-slimpj/"
  tokenizer: "meta-llama/Llama-2-7b-hf"
model:
  attn_backend: splash
  type: llama
# TODO: uncomment this once we resolve the resource exhaustion issue
# initialize_from_hf: "meta-llama/Llama-2-7b-hf"
# use_hf_model_config: true
trainer:
  tracker:
    type: wandb
    project: "levanter"
    tags: ["openwebtext", "llama"]

  mp: p=f32,c=bfloat16
  train_batch_size: 256 # set for v4-64 TPU
  num_train_steps: 20
  steps_per_eval: 50
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: None
  batch_axis: "batch"
  profiler: True
  profiler_num_steps: 10
optimizer:
  learning_rate: 1.2E-5 # set low for fine-tuning
  weight_decay: 0.1
  min_lr_ratio: 0.1
