data:
  id: "DKYoon/SlimPajama-6B"
  cache_dir: "gs://levanter-will-data/tokenized/llama3-slimpj/"
  tokenizer: "meta-llama/Meta-Llama-3-8B"
model:
  type: "llama"
  seq_len: 8192
  hidden_dim: 4096
  num_layers: 32
  num_heads: 32
  num_kv_heads: 8
  rope_base: 500000.0
  intermediate_dim: 14336
  reference_checkpoint: "meta-llama/Meta-Llama-3-8B"
  tokenizer: "meta-llama/Meta-Llama-3-8B"

# TODO: uncomment this once we resolve the resource exhaustion issue
# initialize_from_hf: "meta-llama/Llama-2-7b-hf"
# use_hf_model_config: true
hf_checkpoint: "meta-llama/Meta-Llama-3-8B"
trainer:
  tracker:
    type: wandb
    project: "levanter"
    tags: ["slimpj", "llama", "eval"]

  mp: p=f32,c=bfloat16
  train_batch_size: 256
  per_device_parallelism: 2

  num_train_steps: 3000
  steps_per_eval: 20
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
